apiVersion: v1
kind: Endpoints
metadata:
  name: glusterfs-cluster
subsets:
# These addresses must be changed for individual environments
# Addresses for the current cluster
- addresses:
  - ip: 10.0.0.105
  - ip: 10.0.1.167
  - ip: 10.0.2.65
  ports:
  - port: 1
    protocol: TCP

