apiVersion: v1
kind: Endpoints
metadata:
  name: glusterfs-cluster
subsets:
# These addresses must be changed for individual environments
# Addresses for the current cluster
- addresses:
  - ip: ${GLUSTER_IP_1}
  - ip: ${GLUSTER_IP_2}
  - ip: ${GLUSTER_IP_3}
  ports:
  - port: 1
    protocol: TCP

