apiVersion: v1
kind: Endpoints
metadata:
  name: glusterfs-cluster
subsets:
# These addresses must be changed for individual environments
# Addresses for the current cluster
- addresses:
  - ip: 10.100.5.10
  - ip: 10.100.6.11
  - ip: 10.100.7.12
  ports:
  - port: 1
    protocol: TCP

