apiVersion: v1
kind: List
items:
- apiVersion: v1
    kind: ConfigMap
    metadata:
      name: cache-config
    data:
      SPRING_CACHE_TYPE: "${IFS_DATA_SERVICE_CACHE_TYPE}"
      SPRING_REDIS_HOST: "${IFS_DATA_SERVICE_REDIS_HOST}"
      SPRING_REDIS_PORT: "${IFS_DATA_SERVICE_REDIS_PORT}"
      IFS_DATA_SERVICE_CACHE_TTL_SECONDS: "${IFS_DATA_SERVICE_CACHE_TTL_SECONDS}"
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    creationTimestamp: null
    name: data-service
  spec:
    replicas: 1
    selector:
      deploymentconfig: data-service
    strategy:
      type: Rolling
      rollingParams:
        timeoutSeconds: 600
        maxSurge: 1 #So Flyway runs on one thread at a time
        maxUnavailable: 0
    template:
      metadata:
        creationTimestamp: null
        labels:
          deploymentconfig: data-service
      spec:
        containers:
        - image: innovateuk/data-service:${dataServiceVersion}
          name: data-service
          livenessProbe:
            httpGet:
              path: /monitoring/health
              port: 8080
            initialDelaySeconds: 120
            periodSeconds: 31
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /monitoring/health
              port: 8080
            initialDelaySeconds: 120
            periodSeconds: 5
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 1
          imagePullPolicy: Always
          env:
          - name: IFS_WEB_BASEURL
            value: 'https://${SHIB_ADDRESS}'
          - name: IDP_REST_BASEURL
            value: 'http://registration-svc:8080'
          - name: JAVA_OPTS
            value: -Xms1500m -Xmx1500m -javaagent:/newrelic.jar
          - name: NEW_RELIC_APP_NAME
            value: "ifs-data-service (${openshiftEnv})"
          - name: NEW_RELIC_LICENSE_KEY
            value: "${NEW_RELIC_LICENCE_KEY}"
          - name: NEW_RELIC_LOG
            value: "STDOUT"
          - name: SPRING_DATASOURCE_TOMCAT_MAX_ACTIVE
            value: "100"
          - name: IFS_EARLY_METRICS_URL
            value: "${IFS_EARLY_METRICS_URL}"
          - name: IFS_DATA_SERVICE_FILE_GRANT_SEND_DELAY_MILLIS
            value: "${IFS_DATA_SERVICE_FILE_GRANT_SEND_DELAY_MILLIS}"
          - name: SPRING_CACHE_TYPE
              valueFrom:
                configMapKeyRef:
                  name: cache-config
                  key: SPRING_CACHE_TYPE
          - name: SPRING_REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: cache-config
                  key: DB_HOST
          - name: SPRING_REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: cache-config
                  key: SPRING_REDIS_PORT
          - name: SPRING_CACHE_TYPE
              valueFrom:
                configMapKeyRef:
                  name: cache-config
                  key: SPRING_CACHE_TYPE
          ports:
          - containerPort: 8080
          resources:
            limits:
              cpu: 2000m
            requests:
              cpu: 400m
              memory: 1500M
          volumeMounts:
          - mountPath: /mnt/ifs_storage
            name: dir-1
        volumes:
          - name: dir-1
            persistentVolumeClaim:
              claimName: ${FILE_UPLOAD_CLAIM}
    test: false
    triggers:
    - type: ConfigChange
  status: {}
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    name: data-service
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      targetPort: 8080
    selector:
      deploymentconfig: data-service
  status:
    loadBalancer: {}
