apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    creationTimestamp: null
    name: zipkin-mysql
  spec:
    replicas: 1
    selector:
      deploymentconfig: zipkin-mysql
    strategy:
      resources: {}
    template:
      metadata:
        creationTimestamp: null
        labels:
          deploymentconfig: zipkin-mysql
      spec:
        containers:
        - env:
          image: openzipkin/zipkin-mysql
          name: zipkin-mysql
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 3306
          volumeMounts:
          - name: mysql-tmp-storage
            mountPath: /var/lib/mysql
          resources:
            requests:
              memory: 500M
            limits:
              memory: 600M
        volumes:
          - emptyDir: {}
            name: mysql-tmp-storage
    test: false
    triggers:
    - type: ConfigChange
  status: {}
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    name: zipkin-database
  spec:
    ports:
    - name: 3306-tcp
      port: 3306
      targetPort: 3306
    selector:
      deploymentconfig: zipkin-mysql
  status:
    loadBalancer: {}
