apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ifs-sysint-file-upload-claim
spec:
  accessModes:
  - ReadWriteMany
  resources:
     requests:
       # storage: 20G
       storage: 500Mi
  selector:
    matchLabels:
      # ifssysint: "ifssysint"
      dev: "dev"
