kind: ConfigMap
apiVersion: v1
metadata:
  name: grant-db-config
data:
  GRANT_DB_URL: "${GRANT_DB_URL}"
  GRANT_DB_USER: "${GRANT_DB_USER}"
  GRANT_DB_PASS: "${GRANT_DB_PASS}"
  GRANT_FLYWAY_LOCATIONS: "${GRANT_FLYWAY_LOCATIONS}"