kind: ConfigMap
apiVersion: v1
metadata:
  name: ldap-config
data:
  LDAP_HOST: "${LDAP_HOST}"
  LDAP_PORT: "${LDAP_PORT}"
  LDAP_PASS: "${LDAP_PASS}"
  LDAP_DOMAIN: "${LDAP_DOMAIN}"
  LDAP_SCHEME: "${LDAP_SCHEME}"
  ONLY_SYNC_LDAP: "${ONLY_SYNC_LDAP}"