apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: db-config
  data:
    DB_NAME: "${DB_NAME}"
    DB_USER: "${DB_USER}"
    DB_PASS: "${DB_PASS}"
    DB_HOST: "${DB_HOST}"
    DB_PORT: "${DB_PORT}"
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: flyway-config
  data:
    FLYWAY_LOCATIONS: "${FLYWAY_LOCATIONS}"
    SYSTEM_USER_UUID: "${SYSTEM_USER_UUID}"
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: ldap-config
  data:
    LDAP_HOST: "${LDAP_HOST}"
    LDAP_PORT: "${LDAP_PORT}"
    LDAP_PASS: "${LDAP_PASS}"
    LDAP_DOMAIN: "${LDAP_DOMAIN}"
    LDAP_SCHEME: "${LDAP_SCHEME}"
    ONLY_SYNC_LDAP: "${ONLY_SYNC_LDAP}"
- apiVersion: v1
  kind: Pod
  metadata:
    name: dbreset
  spec:
    containers:
    - name: dbreset
      image: innovateuk/dbreset:1.0-SNAPSHOT
      imagePullPolicy: Always
      command: [ "/bin/bash", "-exec" ]
      args:
      - |
        cat > /flyway/flyway.conf <<EOF
        spring.flyway.url=jdbc:mysql://\${DB_HOST}:\${DB_PORT}
        spring.flyway.schemas=\$DB_NAME
        spring.flyway.locations=\$FLYWAY_LOCATIONS
        spring.flyway.placeholders.ifs.system.user.uuid=\$SYSTEM_USER_UUID
        spring.flyway.user=\$DB_USER
        spring.flyway.password=\$DB_PASS
        EOF
        . /clean-migrate-db-sync-ldap.sh
      env:
      - name: DB_HOST
        valueFrom:
          configMapKeyRef:
            name: db-config
            key: DB_HOST
      - name: DB_PORT
        valueFrom:
          configMapKeyRef:
            name: db-config
            key: DB_PORT
      - name: DB_NAME
        valueFrom:
          configMapKeyRef:
            name: db-config
            key: DB_NAME
      - name: DB_USER
        valueFrom:
          configMapKeyRef:
            name: db-config
            key: DB_USER
      - name: DB_PASS
        valueFrom:
          configMapKeyRef:
            name: db-config
            key: DB_PASS
      - name: LDAP_HOST
        valueFrom:
          configMapKeyRef:
            name: ldap-config
            key: LDAP_HOST
      - name: LDAP_PORT
        valueFrom:
          configMapKeyRef:
            name: ldap-config
            key: LDAP_PORT
      - name: LDAP_PASS
        valueFrom:
          configMapKeyRef:
            name: ldap-config
            key: LDAP_PASS
      - name: LDAP_DOMAIN
        valueFrom:
          configMapKeyRef:
            name: ldap-config
            key: LDAP_DOMAIN
      - name: ONLY_SYNC_LDAP
        valueFrom:
          configMapKeyRef:
            name: ldap-config
            key: ONLY_SYNC_LDAP
      - name: LDAP_SCHEME
        valueFrom:
          configMapKeyRef:
            name: ldap-config
            key: LDAP_SCHEME
      - name: FLYWAY_LOCATIONS
        valueFrom:
          configMapKeyRef:
            name: flyway-config
            key: FLYWAY_LOCATIONS
      - name: SYSTEM_USER_UUID
        valueFrom:
          configMapKeyRef:
            name: flyway-config
            key: SYSTEM_USER_UUID
    restartPolicy: Never